In [17]:
from importlib import reload
import transfermarkt_utils

reload(transfermarkt_utils)
from transfermarkt_utils import *

In [18]:
prem_url = (
    "https://www.transfermarkt.com/"
    "premier-league/startseite/wettbewerb/GB1/plus/?saison_id=2025"
)

prem_clubs = get_league_clubs(prem_url)
prem_clubs.head()

,club_name,club_id,squad_url
0,Afc Bournemouth,989,https://www.transfermarkt.com/afc-bournemouth/...
1,Arsenal Fc,11,https://www.transfermarkt.com/arsenal-fc/kader...
2,Aston Villa,405,https://www.transfermarkt.com/aston-villa/kade...
3,Brentford Fc,1148,https://www.transfermarkt.com/brentford-fc/kad...
4,Brighton And Hove Albion,1237,https://www.transfermarkt.com/brighton-amp-hov...

In [19]:
len(prem_clubs)

20

In [20]:
prem_df = collect_league_squads(
    prem_clubs,
    "2526"
)

✓ Afc Bournemouth
✓ Arsenal Fc
✓ Aston Villa
✓ Brentford Fc
✓ Brighton And Hove Albion
✓ Burnley Fc
✓ Chelsea Fc
✓ Crystal Palace
✓ Everton Fc
✓ Fulham Fc
✓ Leeds United
✓ Liverpool Fc
✓ Manchester City
✓ Manchester United
✓ Newcastle United
✓ Nottingham Forest
✓ Sunderland Afc
✓ Tottenham Hotspur
✓ West Ham United
✓ Wolverhampton Wanderers

In [21]:
prem_df.shape

(555, 6)

In [22]:
prem_df.sample(20)

,player_name,position,Age,market_value_eur,club,season
458,Granit Xhaka,Defensive Midfield,33.0,8000000.0,Sunderland Afc,2526
362,Erling Haaland,Centre-Forward,25.0,200000000.0,Manchester City,2526
300,Brenden Aaronson,Attacking Midfield,25.0,22000000.0,Leeds United,2526
549,Tawanda Chirewa,Attacking Midfield,22.0,450000.0,Wolverhampton Wanderers,2526
500,Dominic Solanke,Centre-Forward,28.0,28000000.0,Tottenham Hotspur,2526
11,Adam Smith,Right-Back,35.0,300000.0,Afc Bournemouth,2526
426,Zach Abbott,Centre-Back,20.0,4000000.0,Nottingham Forest,2526
545,Tommy Doyle,Central Midfield,24.0,7000000.0,Wolverhampton Wanderers,2526
13,Alex Scott,Central Midfield,22.0,50000000.0,Afc Bournemouth,2526
15,Lewis Cook,Central Midfield,29.0,11000000.0,Afc Bournemouth,2526
149,Quilindschy Hartman,Left-Back,24.0,16000000.0,Burnley Fc,2526
533,Yerson Mosquera,Centre-Back,25.0,12000000.0,Wolverhampton Wanderers,2526
40,Martin Ødegaard,Attacking Midfield,27.0,65000000.0,Arsenal Fc,2526
467,Romaine Mundle,Left Winger,23.0,7000000.0,Sunderland Afc,2526
52,Ezri Konsa,Centre-Back,28.0,40000000.0,Aston Villa,2526
445,Taiwo Awoniyi,Centre-Forward,28.0,8000000.0,Nottingham Forest,2526
322,Ryan Gravenberch,Defensive Midfield,24.0,80000000.0,Liverpool Fc,2526
76,Caoimhín Kelleher,Goalkeeper,27.0,28000000.0,Brentford Fc,2526
292,Jayden Bogle,Right-Back,25.0,15000000.0,Leeds United,2526
238,Adam Aznou,Left-Back,20.0,6000000.0,Everton Fc,2526

In [23]:
prem_df["club"].nunique()

20

In [24]:
url = prem_clubs.loc[
    prem_clubs["club_name"] == "Brentford Fc",
    "squad_url"
].iloc[0]

tables = pd.read_html(url)

tables[1].head(20)

      #                         Player   Age  Nat.    Contract Market value
0     1   Caoimhín Kelleher Goalkeeper  27.0   NaN  30/06/2030      €28.00m
1   NaN              Caoimhín Kelleher   NaN   NaN         NaN          NaN
2   NaN                     Goalkeeper   NaN   NaN         NaN          NaN
3    12  Hákon Valdimarsson Goalkeeper  24.0   NaN  30/06/2030       €2.50m
4   NaN             Hákon Valdimarsson   NaN   NaN         NaN          NaN
5   NaN                     Goalkeeper   NaN   NaN         NaN          NaN
6     -         Matthew Cox Goalkeeper  23.0   NaN  30/06/2028        €700k
7   NaN                    Matthew Cox   NaN   NaN         NaN          NaN
8   NaN                     Goalkeeper   NaN   NaN         NaN          NaN
9    31     Ellery Balcombe Goalkeeper  26.0   NaN  30/06/2027        €400k
10  NaN                Ellery Balcombe   NaN   NaN         NaN          NaN
11  NaN                     Goalkeeper   NaN   NaN         NaN          NaN
12   41     Julian Eyestone Goalkeeper  20.0   NaN  30/06/2031            -
13  NaN                Julian Eyestone   NaN   NaN         NaN          NaN
14  NaN                     Goalkeeper   NaN   NaN         NaN          NaN
15    4  Sepp van den Berg Centre-Back  24.0   NaN  30/06/2029      €32.00m
16  NaN              Sepp van den Berg   NaN   NaN         NaN          NaN
17  NaN                    Centre-Back   NaN   NaN         NaN          NaN
18   22     Nathan Collins Centre-Back  25.0   NaN  30/06/2029      €30.00m
19  NaN                 Nathan Collins   NaN   NaN         NaN          NaN

In [25]:
brentford_df = tables[1]

brentford_df[
    brentford_df["Market value"].notna()
][["Player", "Market value"]].tail(10)

                                 Player Market value
63     Keane Lewis-Potter Left Midfield      €25.00m
66  Mikkel Damsgaard Attacking Midfield      €30.00m
69    Antoni Milambo Attacking Midfield      €15.00m
72    Fábio Carvalho Attacking Midfield       €8.00m
75             Kevin Schade Left Winger      €35.00m
78             Reiss Nelson Left Winger       €8.00m
81          Dango Ouattara Right Winger      €35.00m
84         Romelle Donovan Right Winger       €3.50m
87           Igor Thiago Centre-Forward      €65.00m
90             Kaye Furo Centre-Forward       €8.00m

In [26]:
brentford_df["position"] = (
    brentford_df["Player"]
    .apply(extract_position)
)

brentford_df[
    brentford_df["position"].isna()
][["Player"]]

                              Player
1                  Caoimhín Kelleher
4                 Hákon Valdimarsson
7                        Matthew Cox
10                   Ellery Balcombe
13                   Julian Eyestone
16                 Sepp van den Berg
19                    Nathan Collins
22                   Kristoffer Ajer
25                     Ethan Pinnock
28                        Rico Henry
31                    Jayden Meghoma
34                    Michael Kayode
37                      Aaron Hickey
40                     Vitaly Janelt
43                       Yunus Konak
46                  Jordan Henderson
49                   Yegor Yarmolyuk
52                    Mathias Jensen
55                      Frank Onyeka
58                      Josh Dasilva
61                      Ryan Trevitt
63  Keane Lewis-Potter Left Midfield
64                Keane Lewis-Potter
65                     Left Midfield
67                  Mikkel Damsgaard
70                    Antoni Milambo
73                    Fábio Carvalho
76                      Kevin Schade
79                      Reiss Nelson
82                    Dango Ouattara
85                   Romelle Donovan
88                       Igor Thiago
91                         Kaye Furo

In [27]:
prem_df.isna().sum()

player_name         0
position            2
Age                 0
market_value_eur    2
club                0
season              0
dtype: int64

In [28]:
prem_df["position"].value_counts()

position
Centre-Back           96
Goalkeeper            66
Centre-Forward        66
Central Midfield      64
Right-Back            49
Defensive Midfield    46
Right Winger          45
Left-Back             43
Attacking Midfield    41
Left Winger           36
Right Midfield         1
Name: count, dtype: int64

In [29]:
prem_df.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/premier_league_2526.csv",
    index=False
)