In [1]:
import pandas as pd

In [2]:
url = "https://www.transfermarkt.com/premier-league/marktwerteverein/wettbewerb/GB1"

tables = pd.read_html(url)

In [3]:
print(len(tables))

14

In [4]:
for i, table in enumerate(tables):
    print(f"\nTABLE {i}")
    print(table.shape)

TABLE 0
(1, 3)

TABLE 1
(21, 10)

TABLE 2
(15, 4)

TABLE 3
(2, 2)

TABLE 4
(2, 2)

TABLE 5
(2, 2)

TABLE 6
(2, 2)

TABLE 7
(2, 2)

TABLE 8
(15, 4)

TABLE 9
(2, 2)

TABLE 10
(2, 2)

TABLE 11
(2, 2)

TABLE 12
(2, 2)

TABLE 13
(2, 2)

### Promising tables:
- Table 1: (21, 10)
- Table 2: (15, 4)
- Table 8: (15, 4)

In [5]:
table_one = tables[1]

table_one.head(20)

,#,wappen,Club,Club.1,League,Value 15/05/2026,Current value,%,Unnamed: 8,Unnamed: 9
0,1.0,NaN,Manchester City,Premier League,€1.31bn,€1.32bn,0.6 %,NaN,NaN,NaN
1,2.0,NaN,Arsenal FC,Premier League,€1.23bn,€1.25bn,1.3 %,NaN,NaN,NaN
2,3.0,NaN,Chelsea FC,Premier League,€1.16bn,€1.11bn,-4.3 %,NaN,NaN,NaN
3,4.0,NaN,Liverpool FC,Premier League,€1.02bn,€939.50m,-8.3 %,NaN,NaN,NaN
4,5.0,NaN,Manchester United,Premier League,€747.15m,€752.35m,0.7 %,NaN,NaN,NaN
5,6.0,NaN,Tottenham Hotspur,Premier League,€802.50m,€700.00m,-12.8 %,NaN,NaN,NaN
6,7.0,NaN,Newcastle United,Premier League,€708.25m,€696.35m,-1.7 %,NaN,NaN,NaN
7,8.0,NaN,Nottingham Forest,Premier League,€568.00m,€577.60m,1.7 %,NaN,NaN,NaN
8,9.0,NaN,Brighton & Hove Albion,Premier League,€494.00m,€567.00m,14.8 %,NaN,NaN,NaN
9,10.0,NaN,AFC Bournemouth,Premier League,€507.10m,€565.70m,11.6 %,NaN,NaN,NaN
10,11.0,NaN,Crystal Palace,Premier League,€541.30m,€553.20m,2.2 %,NaN,NaN,NaN
11,12.0,NaN,Aston Villa,Premier League,€547.50m,€531.50m,-2.9 %,NaN,NaN,NaN
12,13.0,NaN,Brentford FC,Premier League,€470.40m,€490.58m,4.3 %,NaN,NaN,NaN
13,14.0,NaN,Everton FC,Premier League,€450.45m,€443.15m,-1.6 %,NaN,NaN,NaN
14,15.0,NaN,Sunderland AFC,Premier League,€381.95m,€386.43m,1.2 %,NaN,NaN,NaN
15,16.0,NaN,West Ham United,Premier League,€362.95m,€364.35m,0.4 %,NaN,NaN,NaN
16,17.0,NaN,Leeds United,Premier League,€346.03m,€358.80m,3.7 %,NaN,NaN,NaN
17,18.0,NaN,Fulham FC,Premier League,€386.95m,€356.20m,-7.9 %,NaN,NaN,NaN
18,19.0,NaN,Wolverhampton Wanderers,Premier League,€277.10m,€283.35m,2.3 %,NaN,NaN,NaN
19,20.0,NaN,Burnley FC,Premier League,€252.65m,€228.40m,-9.6 %,NaN,NaN,NaN

In [6]:
table_two = tables[2]

table_two.head(20)

      #                     Player  Club Market value
0   1.0  William SalibaCentre-Back   NaN     €100.00m
1   NaN             William Saliba   NaN          NaN
2   NaN                Centre-Back   NaN          NaN
3   2.0         GabrielCentre-Back   NaN      €75.00m
4   NaN                    Gabriel   NaN          NaN
5   NaN                Centre-Back   NaN          NaN
6   3.0  Josko GvardiolCentre-Back   NaN      €70.00m
7   NaN             Josko Gvardiol   NaN          NaN
8   NaN                Centre-Back   NaN          NaN
9   4.0      Marc GuéhiCentre-Back   NaN      €70.00m
10  NaN                 Marc Guéhi   NaN          NaN
11  NaN                Centre-Back   NaN          NaN
12  5.0      Rúben DiasCentre-Back   NaN      €55.00m
13  NaN                 Rúben Dias   NaN          NaN
14  NaN                Centre-Back   NaN          NaN

In [8]:
table_eight = tables[8]

table_eight.head(20)

      #                         Player  Club Market value
0   1.0   Erling HaalandCentre-Forward   NaN     €200.00m
1   NaN                 Erling Haaland   NaN          NaN
2   NaN                 Centre-Forward   NaN          NaN
3   2.0    Declan RiceCentral Midfield   NaN     €120.00m
4   NaN                    Declan Rice   NaN          NaN
5   NaN               Central Midfield   NaN          NaN
6   3.0        Bukayo SakaRight Winger   NaN     €110.00m
7   NaN                    Bukayo Saka   NaN          NaN
8   NaN                   Right Winger   NaN          NaN
9   4.0      William SalibaCentre-Back   NaN     €100.00m
10  NaN                 William Saliba   NaN          NaN
11  NaN                    Centre-Back   NaN          NaN
12  5.0  Cole PalmerAttacking Midfield   NaN     €100.00m
13  NaN                    Cole Palmer   NaN          NaN
14  NaN             Attacking Midfield   NaN          NaN